spring:
  profiles:
    active: dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: micro-config-dev
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://localhost-dev:7001/eureka
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: micro-config-test
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://localhost-test:7001/eureka